ALTER TABLE public.team_match_stats
  ADD COLUMN IF NOT EXISTS long_balls INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed_long_balls INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_own_third INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_middle_third INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_final_third INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.player_match_stats
  ADD COLUMN IF NOT EXISTS offsides INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fouled INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS long_balls INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS completed_long_balls INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_own_third INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_middle_third INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS passes_final_third INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS claims INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS successful_claims INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS punches INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sweeper_actions INTEGER NOT NULL DEFAULT 0;
